version: "3"

services:
  fast-api:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - MODULE_NAME=main
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8000/api/v1/health"
      interval: 30s
      timeout: 10s
      retries: 2
    env_file:
      - docker-compose.env
  
  postgres:
    image: "postgres:latest"
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pokemon
      POSTGRES_USER: trainer
    volumes:
      - ./resource/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U trainer"]
      interval: 2s
      timeout: 5s
      retries: 2
    
    

