version: "3"

services:
  fast-api:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - MODULE_NAME=main
    healthcheck:
      test: "curl -f http://localhost:8000/api/v1/health"
      interval: 30s
      timeout: 10s
      retries: 2
    env_file:
      - .env
  
  postgres:
    image: "postgres:latest"
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pokemon
      POSTGRES_USER: trainer
    volumes:
      - ./resource/db_create.sql:/docker-entrypoint-initdb.d/db_create.sql
      - ./resource/pokemon-table-data.csv:/docker-entrypoint-initdb.d/pokemon-table-data.csv
    
    

